notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - 2.7

services:
  - docker

before_install:
  - travis_retry pip install yadage

script:
  - yadage-validate workflow/yadage/workflow.yaml | grep -q 'workflow validates'
  - docker run -i -t --rm -v `pwd`:/workdir reanahub/reana-env-jupyter bash -c '
      cd /workdir &&
      mkdir -p ./results &&
      papermill ./code/worldpopulation.ipynb /dev/null
        -p input_file ./data/World_historical_and_predicted_populations_in_percentage.csv
        -p output_file ./results/plot.png
        -p region Europe
        -p year_min 1600
        -p year_max 2010'
  - ls -l `pwd`/results/plot.png
