notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - 2.7

services:
  - docker

before_install:
  - travis_retry pip install yadage

install:
  - docker build -t worldpopulation .

script:
  - yadage-validate world_population_analysis.yaml | grep -q 'workflow validates'
  - docker run -v `pwd`:/code -i -t --rm worldpopulation jupyter nbconvert world_population_analysis.ipynb
  - ls -l world_population_analysis.html
