notifications:
  email: false

sudo: true

language: python

cache:
  - pip

python:
  - 2.7

services:
  - docker

before_install:
  - travis_retry pip install yadage

script:
  - yadage-validate workflow/yadage/workflow.yaml | grep -q 'workflow validates'
  - docker run -i -t --rm -v `pwd`/code:/code -v `pwd`/inputs:/inputs -v `pwd`/outputs:/outputs reanahub/reana-env-jupyter papermill /code/worldpopulation.ipynb /dev/null
  - ls -l `pwd`/outputs/plot.png
