stages:
  - name: worldpopulation
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        outputdir: '{workdir}'
        outputfile: '{workdir}/world_population_analysis.html'
      step:
        process:
          process_type: 'string-interpolated-cmd'
          cmd: 'jupyter nbconvert --output-dir="{outputdir}" world_population_analysis.ipynb'
        publisher:
          publisher_type: 'frompar-pub'
          outputmap:
            outputfile: outputfile
        environment:
          environment_type: 'docker-encapsulated'
          image: 'reanahub/reana-demo-worldpopulation'
