stages:
  - name: worldpopulation
    dependencies: [init]
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        notebook: {stages: init, output: notebook, unwrap: true}
        region: {stages: init, output: region, unwrap: true}
        year_min: {stages: init, output: year_min, unwrap: true}
        year_max: {stages: init, output: year_max, unwrap: true}
        input_file: {stages: init, output: input_file, unwrap: true}
        outputfile: '{workdir}/plot.png'
      step:
        process:
          process_type: 'string-interpolated-cmd'
          cmd: 'papermill "{notebook}" /dev/null -p input_file "{input_file}" -p region "{region}" -p year_min "{year_min}" -p year_max "{year_max}" -p output_file "{outputfile}"'
        publisher:
          publisher_type: 'frompar-pub'
          outputmap:
            outputfile: outputfile
        environment:
          environment_type: 'docker-encapsulated'
          image: 'reanahub/reana-env-jupyter'
