metadata:
  author: "REANA Developers."
  title: "World-population REANA demo in CWL"
environment:
  - type: docker
    image: reanahub/reana-demo-worldpopulation
workflow:
  type: cwl
  file: world_population_analysis.cwl
parameters:
  input: world_population_analysis_job.yml
